### ISSUE TITLE
请问视频支持哪些格式？

### ISSUE THREAD

**Issue by jtyoui** [xdlumia/vue3-video-play#16]
up主，我现在测试的视频格式只能是：`mp4`格式，请问现在支持多少格式？能否出一个列表：如
- MP4
- AVI
- AV4
- 等等

**Comment by xdlumia** [comment]
https://dreamwq.com/vue3-video-play/guide/install.html#hls-m3u8%E8%A7%86%E9%A2%91-%E7%9B%B4%E6%92%AD
看一下这里  基于hls 的m3u8支持

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2021年9月22日 11:20
收件人: ***@***.***>
抄送: ***@***.***>
主题: [xdlumia/vue3-video-play] 请问视频支持哪些格式？ (#16)


up主，我现在测试的视频格式只能是：mp4格式，请问现在支持多少格式？能否出一个列表：如

  *   MP4
  *   AVI
  *   AV4
  *   等等

―

**Comment by jtyoui** [comment]
@xdlumia 请问怎么才能将不同视频格式都统一处理成`m3u8`格式？是否有统一的API可以调用？还是说要自己去实现？

**Comment by jtyoui** [comment]
我发现一个问题，就是在加载视频的时候，无法显示`视频按钮`，一片漆黑。这是否属于正常？
![image](https://user-images.githubusercontent.com/28988355/134302271-f8776261-bdb5-4c8a-8e84-1f040796195c.png)

**Comment by xdlumia** [comment]
视频缓存成功会才会出现操作按钮。如果想缓冲之前就想看到缓存按钮 或者修改loading 背景色 可以修改 .d-loading 的样式

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2021年9月22日 15:39
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [xdlumia/vue3-video-play] 请问视频支持哪些格式？ (#16)


我发现一个问题，就是在加载视频的时候，无法显示视频按钮，一片漆黑。这是否属于正常？
[image]<https://user-images.githubusercontent.com/28988355/134302271-f8776261-bdb5-4c8a-8e84-1f040796195c.png>

―

**Comment by jtyoui** [comment]
我找到你的源代码，已经修改了背景色和颜色，缓存颜色已经改变，但是这并不是我想要的。我想要的是缓存的时候能显示：`操作按钮`.....
```css
.d-loading[data-v-b2384226] {
    position: absolute;
    left: 0;
    right: 0;
    bottom: 0px;
    top: 0;
    display: flex;
    align-items: center;
    justify-content: center;
    background: rgba(227, 7, 91, 0.3);
    z-index: 2;
    color: #2dce09;
    text-align: center;
    font-size: 13px
}
```
![image](https://user-images.githubusercontent.com/28988355/134305558-be30f9ed-1fd4-44d8-95df-d0091a1326c3.png)
